; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nano33ble


[env:uno]
platform = atmelavr
board = uno
framework = arduino
build_flags = -DSERIAL_PORT=Serial -DSERIAL_BAUD=9600 
; upload_flags = -f
; monitor_filters = printable
lib_deps =
  contrem/arduino-timer@^3.0.1

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
upload_protocol = sam-ba
; debug_tool = jlink
; test framwork currently not working.
test_framework = custom
build_flags = -DSERIAL_PORT=Serial -DSERIAL_BAUD=9600  -DMBED=1
