; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = uno

[env:uno]
platform = atmelavr
board = uno
framework = arduino
; upload_flags = -f
; monitor_filters = printable

[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
; upload_port = cu.usbmodem10
; upload_protocol = usbtiny
; upload_flags = -e -F
; monitor_port = usb

; GDB stub implementation
; lib_deps =
;     jdolinay/avr-debugger @ ~1.4

[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
upload_protocol = jlink
debug_tool = jlink
; test framwork currently not working.
test_framework = custom
